### ISSUE TITLE
document small tasks ideas for new contributors

### ISSUE THREAD

**Issue by tnielens** [pityka/saddle#311]
Hi @pityka,

Do you have some tasks in mind for the project? Especially smaller ones that new contributors can potentially handle?
If so, don't hesitate to document them somewhere and/or create github issues :).

Cheers

**Comment by pityka** [comment]
Actually not much :). I consider the library reasonably complete, at least I did not have the need to add new features in the last few months. I definitely plan to maintain it (fix bugs, merge PR), but I don't plan new features. If you need some missing features I am happy discuss them.
