### ISSUE TITLE
`ScalarTagAny` issues with missing values

### ISSUE THREAD

**Issue by tnielens** [pityka/saddle#368]
Unexpected: `ScalarTagChar.isMissing(na.to[Char])` returns `false`. 

I noticed this by by testing `Vec[Char]('a', 'b', na).fillFoward()` which didn't yield the result expected.

**Comment by pityka** [comment]
I think that na object should be removed.

**Comment by tnielens** [comment]
Is there any alternative to `na`? Another surprising behavior I noticed is that `Vec[1, 2, na]` infers `T`as `Any` yielding to issues down the line because the `na` relies on implicit conversion to an `AnyVal`, and is not expected to be found in saddle structures.

**Comment by pityka** [comment]
The alternative is scalarTag.missing and that works well. 

Or using directly the missing value if the code is not polymorphic. Eg Double.NaN.

**Comment by tnielens** [comment]
I think the issues lies the usage of null for representing missing values for Byte, Char, Float, etc in `ScalaTag{Byte,Char,Float}`. These primitives aren't specialized for in saddle structures and will box as soon as they are manipulated in Vec, Series, etc. The issue is that `null` isn't preserved after an unboxing and reboxing cycle. 

More concretely, when calling `ScalarTagChar.missing`, scala/the jvm turns the underlying null pointer, into the default Char value, which is '\u000'. When passing that value to `ScalarTagChar.isMissing(c)`, the value is reboxed, not as null, but as a regular boxed Char. Here are some examples to illustrate the problem:

```scala
@ scalar.ScalarTagChar.missing 
res1: Char = '\u0000'

// doesn't seem to unbox and rebox
@ scalar.ScalarTagChar.isMissing(scalar.ScalarTagChar.missing) 
res2: Boolean = true

// unbox
val m = scalar.ScalarTagChar.missing 
m: Char = '\u0000'
// rebox
scalar.ScalarTagChar.isMissing(m) 
res3: Boolean = false
```

One solution to tackle this issue would be to use `<primitive>.MinValue` instead of `null` for representing missing value of unspecialized primitives (Char, Byte, etc) like done for specialized primitives.

**Comment by pityka** [comment]
I think you are correct. Those STs should have a simolar implementation as Double or Int.
