### ISSUE TITLE
Cross product in Frame.apply

### ISSUE THREAD

**Issue by pityka** [pityka/saddle#381]
```scala
Frame(
  Series(0 -> 1,2 -> 2, 1 -> 3, 0 -> 4),
  Series(1 -> 1,2 -> 2, 0 -> 3, 0 -> 4),
  Series(0 -> 1,1 -> 2, 2 -> 3, 0 -> 4)
)
```

yields
```
val res3: org.saddle.Frame[Int,Int,Int] =
[10 x 3]
      0  1  2
     -- -- --
0 ->  1  3  1
0 ->  1  3  4
0 ->  1  4  1
0 ->  1  4  4
0 ->  4  3  1
0 ->  4  3  4
0 ->  4  4  1
0 ->  4  4  4
2 ->  2  2  3
1 ->  3  1  2
```

If the row indices are not the same and they contain duplicates then it is doing a series of cross products. This is looses no data and from a certain pespective this is correct. However it is rarely the expected behavior and on any medium sized data it blows up.

**Comment by pityka** [comment]
@tnielens what do you think of this? I am bumping into this issue very often. IMO it would be better to have an explicit opt-in into this risky behavior. Otherwise the default behaviour should throw an exception quickly if duplicates are found, rathern than risking eating up the heap

**Comment by tnielens** [comment]
For comparison, here is the pandas behavior: 
```python
import pandas as pd

a = pd.Series([1, 1, 1], index=[1, 1, 1])
b = pd.Series([1, 1, 1], index=[1, 1, 2])
a + b
# Output: 
# 1    2.0
# 1    2.0
# 1    2.0
# 1    2.0
# 1    2.0
# 1    2.0
# 2    NaN
# dtype: float64


pd.DataFrame({"a": a, "b": b})
# Output:
# ValueError: cannot reindex on an axis with duplicate labels
```

So adding series behaves as a cross product, but constructing a frame requires indices with unique keys.
Mabye saddle could indeed crash for non-unique indices in the default constructor, but there could be an extra constructor `Frame.join(Seq[Series], j: JoinType)`. This joins your suggestion of an explicit opt-in.
